### ISSUE TITLE
failed to locate view "index.jade"

### ISSUE THREAD

**Issue by 75lb** [fcsonline/nodestalgia#20]
Hi, just installed nodestalgia.. failed to run out of the box.. output below, cheers. 

```
$ nodestalgia web.log 
path.existsSync is now called `fs.existsSync`.
   info  - socket.io started
Express server listening on port 8081 in development mode

failed to locate view "index.jade", tried:
  - /usr/local/lib/node_modules/nodestalgia/bin/views/index.jade
  - /usr/local/lib/node_modules/nodestalgia/bin/views/index/index.jade
  - /usr/local/lib/node_modules/nodestalgia/bin/views/../index/index.jade

Error: failed to locate view "index.jade"
    at Function.exports.compile (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:61:15)
    at ServerResponse.res._render (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:417:18)
    at ServerResponse.res.render (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:318:17)
    at /usr/local/lib/node_modules/nodestalgia/routes/index.js:8:9
    at callbacks (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:272:11)
    at param (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:246:11)
    at pass (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:280:5)
    at Object.Router.middleware [as handle] (/usr/local/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:45:10)
    at next (/usr/local/lib/node_modules/nodestalgia/node_modules/express/node_modules/connect/lib/http.js:204:15)
```

**Comment by kfatehi** [comment]
bump; I am experiencing the same issue

## commands

```
➜  ~  node -v
v0.8.18
➜  ~  npm install nodestalgia -g
...
➜  ~  nodestalgia
   info  - socket.io started
Express server listening on port 8081 in development mode
```

## localhost:8081 output

```
Express
500 Error: failed to locate view "index.jade"
at Function.exports.compile (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:61:15)
at ServerResponse.res._render (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:417:18)
at ServerResponse.res.render (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:318:17)
at /usr/local/share/npm/lib/node_modules/nodestalgia/routes/index.js:8:9
at callbacks (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:272:11)
at param (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:246:11)
at pass (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:253:5)
at Router._dispatch (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:280:5)
at Object.middleware [as handle] (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:45:10)
at next (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/node_modules/connect/lib/http.js:204:15)
```

## console output upon request to localhost:8081

```
failed to locate view "index.jade", tried:
  - /usr/local/share/npm/lib/node_modules/nodestalgia/bin/views/index.jade
  - /usr/local/share/npm/lib/node_modules/nodestalgia/bin/views/index/index.jade
  - /usr/local/share/npm/lib/node_modules/nodestalgia/bin/views/../index/index.jade

Error: failed to locate view "index.jade"
    at Function.exports.compile (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:61:15)
    at ServerResponse.res._render (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:417:18)
    at ServerResponse.res.render (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/view.js:318:17)
    at /usr/local/share/npm/lib/node_modules/nodestalgia/routes/index.js:8:9
    at callbacks (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:272:11)
    at param (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:246:11)
    at pass (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:280:5)
    at Object.middleware [as handle] (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/lib/router/index.js:45:10)
    at next (/usr/local/share/npm/lib/node_modules/nodestalgia/node_modules/express/node_modules/connect/lib/http.js:204:15)
```

**Comment by 75lb** [comment]
just install logstalgia instead: 

```
$ brew install logstalgia
```

then use `local-web-server` in tandem to give you a live visualisation: https://github.com/75lb/local-web-server

**Comment by kfatehi** [comment]
Thanks but my use case is to serve an HTML5 page showing the graphic in the browser
